# Generated by Django 5.1.7 on 2025-05-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'jmate_signin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('support_info', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('to_location', models.TextField()),
                ('to_latitude', models.FloatField(blank=True, null=True)),
                ('to_longitude', models.FloatField(blank=True, null=True)),
                ('to_area', models.CharField(blank=True, max_length=100, null=True)),
                ('to_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('request_accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jmate_SupportEntry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pas_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('support_info', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('to_location', models.TextField()),
                ('to_latitude', models.FloatField(blank=True, null=True)),
                ('to_longitude', models.FloatField(blank=True, null=True)),
                ('to_area', models.CharField(blank=True, max_length=100, null=True)),
                ('to_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_driver', models.CharField(blank=True, max_length=15, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jmate_pas_Entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JMate.supportentry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JMate.pas_entry')),
            ],
        ),
    ]
